server:
  port: 9001
#LRU,LFU,FIFO,CLOCK

ehcache:
  eviction:
    policy: LRU


  max:
    local:
      heap: 1000


  time:
    to:
      live: "20"

  enabled: true

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mydb?useSSL=false

    username: root

    password: root

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

    hibernate:
      ddl-auto: validate
